import { basename, resolve } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { Deps } from "./types";

export function registerExploreCommands(pi: ExtensionAPI, deps: Deps) {
  pi.registerCommand("memory.codebase.root", { description: "Set/show codebase root: /memory.codebase.root set <root-path> [domain-id] | show", handler: async (args, ctx) => { const raw = (args || "").trim(); const store = deps.getStore(); if (!raw || raw === "show") { const active = deps.activeDomainId(ctx.cwd) || "(none)"; const list = Object.entries(store.domains || {}).map(([id, roots]) => `${id}: ${(roots as string[]).join(", ")}`).join("\n") || "(no roots)"; return ctx.ui.notify(`Active domain: ${active}\n${list}`, "info"); } const m = raw.match(/^set\s+(?:"([^"]+)"|'([^']+)'|(\S+))(?:\s+(\S+))?$/i); if (!m) return ctx.ui.notify("Usage: /memory.codebase.root set <root-path> [domain-id]", "error"); const rootPath = m[1] || m[2] || m[3]; const domainArg = m[4]; const root = resolve(ctx.cwd, rootPath); const domain = (domainArg || basename(root)).toLowerCase(); deps.bindDomainRoot(domain, root); deps.clearPendingRootConfirm(); await deps.persist(); ctx.ui.notify(`Set codebase root ${root} for domain ${domain}`, "info"); } });

  pi.registerCommand("memory.explore", { description: "Explore codebase and save shared domain knowledge: /memory.explore [--deep] [root-path] [domain-id]", handler: async (args, ctx) => { const rawParts = (args || "").trim().split(/\s+/).filter(Boolean); const deep = rawParts.includes("--deep"); const parts = rawParts.filter((p) => p !== "--deep"); let root = ""; let domainId = ""; if (parts.length > 0) root = resolve(ctx.cwd, parts[0]); if (parts.length > 1) domainId = parts[1].toLowerCase(); if (!root) { const active = deps.rootForCwd(ctx.cwd); root = active.root || ctx.cwd; domainId = domainId || active.domainId || basename(root).toLowerCase(); } else domainId = domainId || deps.activeDomainId(root) || basename(root).toLowerCase(); const store = deps.getStore(); if (!store.domains[domainId] || !store.domains[domainId].some((r: string) => deps.normalizePath(r) === deps.normalizePath(root))) { deps.bindDomainRoot(domainId, root); await deps.persist(); ctx.ui.notify(`Auto-confirmed root ${root} for domain ${domainId}`, "info"); } const info = await deps.scanCodebase(root, domainId, deep); await deps.persist(); const cov = info.coverage ? ` coverage=${info.coverage.coveredCount}/${info.coverage.visitedCount} unknown=${info.coverage.unknownCount} stale=${info.coverage.staleCount}` : ""; ctx.ui.notify(`Explored ${info.root} (domain ${info.domainId}) services=${info.services} memories=${info.items}${cov}${deep ? " [deep]" : ""}`, "info"); } });

  pi.registerCommand("memory.snapshot", { description: "Create full feature-ready codebase snapshot in memory: /memory.snapshot [--deep] [root-path] [domain-id]", handler: async (args, ctx) => { const rawParts = (args || "").trim().split(/\s+/).filter(Boolean); const deep = rawParts.includes("--deep"); const parts = rawParts.filter((p) => p !== "--deep"); let root = ""; let domainId = ""; if (parts.length > 0) root = resolve(ctx.cwd, parts[0]); if (parts.length > 1) domainId = parts[1].toLowerCase(); if (!root) { const active = deps.rootForCwd(ctx.cwd); root = active.root || ctx.cwd; domainId = domainId || active.domainId || basename(root).toLowerCase(); } else domainId = domainId || deps.activeDomainId(root) || basename(root).toLowerCase(); const store = deps.getStore(); if (!store.domains[domainId] || !store.domains[domainId].some((r: string) => deps.normalizePath(r) === deps.normalizePath(root))) deps.bindDomainRoot(domainId, root); const info = await deps.snapshotCodebase(root, domainId, deep); await deps.persist(); ctx.ui.notify(`Snapshot saved for ${info.root} (domain ${info.domainId}) files=${info.files} memories=${info.items}`, "info"); } });
}
