import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { Deps } from "./types";
import { makeScopedMemoryItem } from "./helpers";

export function registerMaintenanceCommands(pi: ExtensionAPI, deps: Deps) {
  pi.registerCommand("memory.decision", { description: "Record decision + rationale: /memory.decision add <decision>|<rationale>|[alternatives]", handler: async (args, ctx) => { const raw = (args || "").trim(); const m = raw.match(/^add\s+(.+)$/i); if (!m) return ctx.ui.notify("Usage: /memory.decision add <decision>|<rationale>|[alternatives]", "error"); const [decision, rationale, alternatives] = m[1].split("|").map((x) => (x || "").trim()); if (!decision || !rationale) return ctx.ui.notify("Usage: /memory.decision add <decision>|<rationale>|[alternatives]", "error"); const store = deps.getStore(); const domainId = deps.activeDomainId(ctx.cwd); store.items.push(makeScopedMemoryItem({ uid: deps.uid, projectKeyOf: deps.projectKeyOf, cwd: ctx.cwd, domainId, kind: "lesson", text: `Decision: ${decision}. Rationale: ${rationale}${alternatives ? `. Alternatives: ${alternatives}` : ""}`, confidence: 0.94, source: "memory_playbook", pinned: true, meta: { playbookCategory: "decision", decision, rationale, alternatives } })); await deps.persist(); ctx.ui.notify("Decision saved", "info"); } });

  pi.registerCommand("memory.playbook", { description: "Show playbook guardrails", handler: async (_args, ctx) => { const store = deps.getStore(); const inScope = store.items.filter((x: any) => x.scope === "global" || x.projectKey === deps.projectKeyOf(ctx.cwd) || (x.scope === "domain" && x.domainId === deps.activeDomainId(ctx.cwd))); const pick = (cat: string, n: number) => inScope.filter((x: any) => String(x.meta?.playbookCategory || "") === cat).slice(-n).reverse().map((x: any) => `- (${x.id}) ${x.text}`).join("\n"); ctx.ui.notify(["Playbook:", "Rules:", pick("code-rule", 8) || "- none", "Standards:", pick("code-standard", 6) || "- none", "Decisions:", pick("decision", 6) || "- none"].join("\n"), "info"); } });
  pi.registerCommand("memory.forget", { description: "Forget by id or text fragment: /memory.forget <id|text>", handler: async (args, ctx) => { const q = (args || "").trim().toLowerCase(); if (!q) return ctx.ui.notify("Usage: /memory.forget <id|text>", "error"); const store = deps.getStore(); const before = store.items.length; store.items = store.items.filter((x: any) => !(x.id === q || x.text.toLowerCase().includes(q))); await deps.persist(); ctx.ui.notify(`Removed ${before - store.items.length} item(s)`, "info"); } });
  pi.registerCommand("memory.preference.confirm", { description: "Increase preference confirmation count: /memory.preference.confirm <id>", handler: async (args, ctx) => { const id = (args || "").trim(); if (!id) return ctx.ui.notify("Usage: /memory.preference.confirm <id>", "error"); const store = deps.getStore(); const hit = store.items.find((x: any) => x.id === id); if (!hit) return ctx.ui.notify("Memory id not found", "error"); const current = Number((hit.meta as any)?.confirmations || 0) + 1; hit.meta = { ...(hit.meta || {}), playbookCategory: (hit.meta as any)?.playbookCategory || "preference", confirmations: current }; if (current >= 3) { hit.meta.playbookCategory = "code-rule"; hit.pinned = true; } hit.updatedAt = Date.now(); await deps.persist(); ctx.ui.notify(`Preference confirmations: ${current}${current >= 3 ? " (promoted to code-rule)" : ""}`, "info"); } });
  pi.registerCommand("memory.prune", { description: "Prune stale/low-value memories: /memory.prune [--dry-run]", handler: async (args, ctx) => { const dryRun = (args || "").includes("--dry-run"); const report = deps.prune(dryRun); if (!dryRun) await deps.persist(); const reasonText = Object.entries(report.reasons).map(([k, v]) => `${k}:${v}`).join(", ") || "none"; ctx.ui.notify(`Prune ${dryRun ? "preview" : "done"}: removed=${report.removed} kept=${report.kept} reasons=[${reasonText}]`, "info"); } });
}
