import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { Deps } from "./types";
import { makeScopedMemoryItem } from "./helpers";

export function registerPlaybookCommands(pi: ExtensionAPI, deps: Deps) {
  pi.registerCommand("memory.pin", { description: "Pin memory item by id: /memory.pin <id>", handler: async (args, ctx) => { const id = (args || "").trim(); if (!id) return ctx.ui.notify("Usage: /memory.pin <id>", "error"); const store = deps.getStore(); const hit = store.items.find((x: any) => x.id === id); if (!hit) return ctx.ui.notify("Memory id not found", "error"); hit.pinned = true; hit.updatedAt = Date.now(); await deps.persist(); ctx.ui.notify(`Pinned ${id}`, "info"); } });
  pi.registerCommand("memory.unpin", { description: "Unpin memory item by id: /memory.unpin <id>", handler: async (args, ctx) => { const id = (args || "").trim(); if (!id) return ctx.ui.notify("Usage: /memory.unpin <id>", "error"); const store = deps.getStore(); const hit = store.items.find((x: any) => x.id === id); if (!hit) return ctx.ui.notify("Memory id not found", "error"); hit.pinned = false; hit.updatedAt = Date.now(); await deps.persist(); ctx.ui.notify(`Unpinned ${id}`, "info"); } });

  pi.registerCommand("memory.rule", { description: "Manage code rules: /memory.rule add <text>", handler: async (args, ctx) => { const raw = (args || "").trim(); const m = raw.match(/^add\s+(.+)$/i); if (!m) return ctx.ui.notify("Usage: /memory.rule add <text>", "error"); const store = deps.getStore(); const domainId = deps.activeDomainId(ctx.cwd); store.items.push(makeScopedMemoryItem({ uid: deps.uid, projectKeyOf: deps.projectKeyOf, cwd: ctx.cwd, domainId, kind: "lesson", text: m[1].trim(), confidence: 0.95, source: "memory_playbook", pinned: true, meta: { playbookCategory: "code-rule" } })); await deps.persist(); ctx.ui.notify("Rule saved", "info"); } });
  pi.registerCommand("memory.standard", { description: "Manage standards: /memory.standard add <text>", handler: async (args, ctx) => { const raw = (args || "").trim(); const m = raw.match(/^add\s+(.+)$/i); if (!m) return ctx.ui.notify("Usage: /memory.standard add <text>", "error"); const store = deps.getStore(); const domainId = deps.activeDomainId(ctx.cwd); store.items.push(makeScopedMemoryItem({ uid: deps.uid, projectKeyOf: deps.projectKeyOf, cwd: ctx.cwd, domainId, kind: "pattern", text: m[1].trim(), confidence: 0.9, source: "memory_playbook", meta: { playbookCategory: "code-standard" } })); await deps.persist(); ctx.ui.notify("Standard saved", "info"); } });
  pi.registerCommand("memory.preference", { description: "Manage preferences: /memory.preference add <text>", handler: async (args, ctx) => { const raw = (args || "").trim(); const m = raw.match(/^add\s+(.+)$/i); if (!m) return ctx.ui.notify("Usage: /memory.preference add <text>", "error"); const store = deps.getStore(); const domainId = deps.activeDomainId(ctx.cwd); store.items.push(makeScopedMemoryItem({ uid: deps.uid, projectKeyOf: deps.projectKeyOf, cwd: ctx.cwd, domainId, kind: "preference", text: m[1].trim(), confidence: 0.9, source: "memory_playbook", meta: { playbookCategory: "preference", confirmations: 1 } })); await deps.persist(); ctx.ui.notify("Preference saved (confirm 1/3)", "info"); } });
}
